services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=real_state_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '5434'
  redis:
    image: 'redis:latest'
    ports:
      - '6379'
